"""add notion_tasks table

Revision ID: ccc98ef052fd
Revises: 0006_add_llm_registry_and_policy
Create Date: 2026-02-13 17:04:14.441407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc98ef052fd'
down_revision = '0006_add_llm_registry_and_policy'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notion_page_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('source_db', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('notes', sa.String(length=4096), nullable=True),
    sa.Column('notion_last_edited', sa.String(length=32), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notion_tasks_domain', 'notion_tasks', ['domain'], unique=False)
    op.create_index('ix_notion_tasks_due_date', 'notion_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_notion_tasks_notion_page_id'), 'notion_tasks', ['notion_page_id'], unique=True)
    op.create_index('ix_notion_tasks_status_priority', 'notion_tasks', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notion_tasks_status_priority', table_name='notion_tasks')
    op.drop_index(op.f('ix_notion_tasks_notion_page_id'), table_name='notion_tasks')
    op.drop_index('ix_notion_tasks_due_date', table_name='notion_tasks')
    op.drop_index('ix_notion_tasks_domain', table_name='notion_tasks')
    op.drop_table('notion_tasks')
    # ### end Alembic commands ###
